### ISSUE TITLE
Toroid mirror error: Modified surface and grazing angles

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/shadow4#31]
Hello,

There is a bug in the **Toroidal mirror** when using a modified surface and low grazing angles, for example:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/37fefe06-bb84-4abe-a0f5-debd94de80e5)
You can find this basic OASYS workflow here: 
[toroid_mirror_error.zip](https://github.com/user-attachments/files/15815346/toroid_mirror_error.zip)

For example:
- For 5.0005 mrad it is fine:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/13ade5d5-b176-44c6-a4ad-f26736ec0192)
- Angle = 5 mrad there is an error:
![image](https://github.com/oasys-kit/shadow4/assets/31166917/adff473d-60b7-4db5-8335-76a84aae054b)
The error seems to be in:
`C:\Users\~\Miniconda3\lib\site-packages\shadow4\optical_surfaces\s4_toroid.py:636: RuntimeWarning: invalid value encountered in sqrt
  t2 = 0.5 * (-B - numpy.sqrt(B**2 - 4 * C))`

I've checked other mirror types and the error is only present in the Toroid type.

Thank you.
Cheers, J

**Comment by srio** [comment]
The problem is related to a subtle mismatch of the inputs:

By reducing the incident angle and automatically calculating the toroid radii, the r_min is getting smaller. If |2 r_min| <  width of the slope error mesh, shadow4 fails to calculate the ideal surface to be added to the mesh surface.

Make sure that the width or the surface error is smaller than 2*r_min.

I added an exception that will appear in this case.  It will appear in the next release.
